#!/usr/bin/env node
// One-off backfill for a single paper-catch source: runs the regular pipeline
// against an isolated output dir with a synthetic config (one URL + the interest
// copied from the base config) and a lookback reaching back to --since. The main
// paper_catch/ state is never touched, so the next regular run keeps its baselines.
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { parseArgs } from "node:util";
import { fileURLToPath } from "node:url";
import { parseCatchConfig, sourceSpecFromUrl } from "./paper_catch/config.ts";
import { PaperCatchStore } from "./paper_catch/store.ts";

const scriptPath = fileURLToPath(import.meta.url);
const projectRoot = resolve(dirname(scriptPath), "..");
const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: {
    url: { type: "string" },
    since: { type: "string" },
    "base-config": { type: "string" },
    template: { type: "string" },
    "output-dir": { type: "string" },
    "batch-size": { type: "string" },
    model: { type: "string" },
    "codex-bin": { type: "string" },
    "no-search": { type: "boolean", default: false },
    "max-attempts": { type: "string" },
    "codex-timeout-ms": { type: "string" },
  },
});

const command = positionals[0] ?? "run";

try {
  if (command !== "run" && command !== "scan" && command !== "status" && command !== "validate") {
    usage();
    process.exitCode = 2;
  } else {
    main(command);
  }
} catch (error) {
  process.stderr.write(`ERROR: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
}

function main(subcommand: string): void {
  if (!values.url) throw new Error("--url is required");
  const spec = sourceSpecFromUrl(values.url);
  const baseConfigPath = resolve(values["base-config"] ?? resolve(projectRoot, "human_notes/Catch_Paper_Urls.md"));
  const base = parseCatchConfig(baseConfigPath);
  const outputDir = resolve(
    values["output-dir"] ?? resolve(projectRoot, "paper_catch", `backfill_${spec.sourceId}`),
  );
  mkdirSync(outputDir, { recursive: true });

  const templatePath = resolve(outputDir, "PAPER_ENTRY_TEMPLATE.md");
  if (!existsSync(templatePath)) {
    const sourceTemplate = resolve(
      values.template ?? resolve(dirname(baseConfigPath), "..", "paper_catch", "PAPER_ENTRY_TEMPLATE.md"),
    );
    if (!existsSync(sourceTemplate)) throw new Error(`entry template not found: ${sourceTemplate}`);
    copyFileSync(sourceTemplate, templatePath);
  }

  const configPath = resolve(outputDir, "config.md");
  const configText = [
    `<!-- generated by scripts/paper_catch_backfill.ts from ${baseConfigPath}; do not edit -->`,
    spec.url,
    "",
    `感兴趣主题：${base.interest}`,
    "",
  ].join("\n");
  if (!existsSync(configPath) || readFileSync(configPath, "utf8") !== configText) {
    writeFileSync(configPath, configText, "utf8");
  }

  const store = new PaperCatchStore(outputDir);
  store.initialize();
  const latest = store.latestReport();
  const forwarded = ["--config", configPath, "--output-dir", outputDir];
  if (subcommand === "run" || subcommand === "scan") {
    if (!values.since) throw new Error("--since YYYY-MM-DD is required for run/scan");
    const since = new Date(values.since);
    if (Number.isNaN(since.getTime())) throw new Error(`invalid --since: ${values.since}`);
    const lookbackDays = Math.max(1, Math.ceil((Date.now() - since.getTime()) / 86_400_000));
    if (latest) {
      process.stderr.write(
        `NOTE: ${outputDir} already has report ${latest.reportRef}; --since is ignored and the run continues from its HEAD sidecar.\n`,
      );
    }
    forwarded.push("--lookback-days", String(lookbackDays));
    process.stderr.write(
      `backfill ${spec.displayName}\n  since=${since.toISOString()} lookback-days=${lookbackDays}\n  config=${configPath}\n  output-dir=${outputDir}\n`,
    );
  }
  for (const key of ["batch-size", "model", "codex-bin", "max-attempts", "codex-timeout-ms"] as const) {
    const value = values[key];
    if (value !== undefined) forwarded.push(`--${key}`, value);
  }
  if (values["no-search"]) forwarded.push("--no-search");

  const result = spawnSync(
    process.execPath,
    [resolve(projectRoot, "scripts/paper_catch.ts"), subcommand, ...forwarded],
    { cwd: projectRoot, stdio: "inherit", env: process.env },
  );
  process.exitCode = result.status ?? 1;
}

function usage(): void {
  process.stderr.write(`Usage:
  node scripts/paper_catch_backfill.ts [run|scan|status|validate] --url URL --since YYYY-MM-DD [options]

Runs paper_catch.ts for exactly one source URL (optionally with a README #fragment)
in an isolated output directory, looking back to --since on the first run. Use
scripts/paper_catch_merge.ts to fold the resulting report into a regular one.

Options:
  --url URL                  Single GitHub source URL, e.g. https://github.com/o/r#section
  --since YYYY-MM-DD         Earliest commit date to consider (first run only)
  --base-config PATH         Where to copy 感兴趣主题 from; default: human_notes/Catch_Paper_Urls.md
  --template PATH            Entry template copied into output-dir once; default: paper_catch/PAPER_ENTRY_TEMPLATE.md next to base-config
  --output-dir PATH          Default: paper_catch/backfill_<sourceId>
  --batch-size, --model, --codex-bin, --no-search, --max-attempts, --codex-timeout-ms
                             Forwarded to paper_catch.ts
`);
}
